name: BigDoorsPhysics
version: '${version}'
main: net.bonn2.bigdoorsphysics.BigDoorsPhysics
api-version: 1.19
depend: [ BigDoors ]
softdepend: [ ProtocolLib ]
authors: [ bonn2 ]
description: Using every trick in the book
commands:
  killbigdoorsphysicsentities:
    description: Kill all entities created by the BigDoorsPhysics plugin
    usage: /<command>
permissions:
  bigdoorsphysics.admin.killentities:
    default: false
    description: Allow killing of all entities created by this plugin